extends:
  - .eslintrc.yml
  - plugin:react/all
  - plugin:react-hooks/recommended
  - plugin:import/react

overrides:
  - files: "*.tsx"
    rules:
      "@typescript-eslint/naming-convention": off
      new-cap: off

rules:
  import/no-unresolved:
    - error
    - ignore:
        - react$
        - react-dom$

  # https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
  react/hook-use-state: off
  react/jsx-filename-extension:
    - error
    - allow: as-needed
      extensions: [.tsx]
  react/jsx-max-depth: off
  react/jsx-max-props-per-line: off
  react/jsx-no-literals: off
  react/jsx-one-expression-per-line:
    - error
    - allow: single-child
  react/prop-types: off
  react-hooks/exhaustive-deps: error

settings:
  react:
    pragma: React
    version: detect
