image: node:19.9

cache:
  paths:
    - .yarn/cache/
    - .yarn/unplugged/
    - .yarn/install-state.gz
    - .pnp.*
    - "*/*/dist/eslint/*"

ci:
  script:
    # https://github.com/parcel-bundler/parcel/issues/8005#issuecomment-1120149358
    - export NODE_OPTIONS=--no-experimental-fetch
    - yarn install --immutable
    - yarn clean
    - yarn prettier
    - yarn git-is-clean
    - yarn build
    - yarn sources
    - yarn git-is-clean

  artifacts:
    paths:
      - extensions/*/dist/webext/*.zip
      - sources.zip

variables:
  BROWSERSLIST_IGNORE_OLD_DATA: "true"
