image: node:17.9.1-alpine

cache:
  paths:
    - .yarn/cache/
    - .yarn/unplugged/
    - .yarn/build-state.yml
    - "*/*/dist/eslint/*"

ci:
  script:
    # necessary with alpine's minimal image
    - apk add --no-cache git make python3 util-linux
    - yarn install --immutable
    - yarn clean
    - yarn prettier
    - yarn git-is-clean
    - yarn build
    - yarn sources
    - yarn git-is-clean

  artifacts:
    paths:
      - extensions/*/dist/webext/*.zip
      - sources.zip
