image: node:20.3

cache:
  paths:
    - .yarn/cache/
    - .yarn/unplugged/
    - .yarn/install-state.gz
    - .pnp.*
    - "*/*/dist/eslint/*"

ci:
  script:
    - yarn install --immutable
    - yarn clean
    - yarn prettier
    - yarn git-is-clean
    - yarn build
    - yarn sources
    - yarn git-is-clean

  artifacts:
    paths:
      - extensions/*/dist/webext/*.zip
      - sources.zip

variables:
  BROWSERSLIST_IGNORE_OLD_DATA: "true"
