image: node:14.18.2-alpine

cache:
  paths:
    - .yarn/cache/
    - .yarn/unplugged/
    - .yarn/build-state.yml

ci:
  script:
    # necessary with alpine's minimal image
    - apk add --no-cache git make python3 util-linux
    - yarn install --immutable
    - yarn clean
    - yarn prettier
    - yarn git-is-clean
    - yarn build
    - yarn bundle
    - yarn git-is-clean

  artifacts:
    paths:
      - extensions/*/dist/*.zip
      - sources.zip
