overrides:
  - files: "*.{md,yml}"
    options:
      tabWidth: 2
# required under optimized package managers until prettier reads package.json for plugins
plugins:
  - prettier-plugin-package
  - prettier-plugin-svelte
proseWrap: always
tabWidth: 4
