arrowParens: avoid
bracketSpacing: false
htmlWhitespaceSensitivity: ignore
overrides:
  - files: "*.{md,yml}"
    options:
      tabWidth: 2
# required under optimized package managers until prettier reads package.json for plugins
plugins:
  - prettier-plugin-package
printWidth: 160
proseWrap: never
tabWidth: 4
trailingComma: none
