packageExtensions:
  addons-linter@*:
    dependencies:
      "@types/download": latest
      body-parser: latest
      download: latest
      express: latest
      safe-compare: latest
  "@parcel/transformer-postcss@*":
    dependencies:
      "postcss": latest
  "@parcel/reporter-dev-server@*":
    dependencies:
      "@types/express": latest
  "@parcel/config-webextension@*":
    dependencies:
      "@parcel/core": ^2.2.1
  "@parcel/optimizer-image@*":
    dependencies:
      "@parcel/core": ^2.2.1
  "@parcel/types@*":
    dependencies:
      "@parcel/core": ^2.2.1
  "@parcel/transformer-image@*":
    dependencies:
      "@parcel/core": ^2.2.1
  "@parcel/transformer-js@*":
    dependencies:
      "@parcel/core": ^2.2.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: "https://yarnplugins.com/echo-execute"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
