packageExtensions:
  addons-linter@*:
    dependencies:
      "@types/download": latest
      body-parser: latest
      download: latest
      express: latest
      safe-compare: latest

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: "https://yarnplugins.com/echo-execute"

yarnPath: .yarn/releases/yarn-2.4.3.cjs
