plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: "https://yarnplugins.com/echo-execute"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "https://raw.githubusercontent.com/yarnpkg/berry/3f901be864fa9001243449765c5e3032a64fb6b9/packages/plugin-workspace-tools/bin/@yarnpkg/plugin-workspace-tools.js"

yarnPath: .yarn/releases/yarn-2.4.3.cjs
